apiVersion: v1
kind: Service
metadata:
  name: {{ include "gerrit.fullname" . }}
  labels:
    {{- include "gerrit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "gerrit.selectorLabels" . | nindent 4 }}
